<html>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<div class="container">

  <div class="row g-3 align-items-center">
    <form action="authorization.php" method="post">

      <div class="row justify-content-md-center">
        <h3>Вход для администратора</h3>
      </div>
      <div class="mb-3">

        <label class="form-label">Логин</label>
        <input type="text" class="form-control" id="login" name="login" value="<?php echo $login; ?>" required>
      </div>

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Пароль</label>
        <input type="password" class="form-control" name="password" id="password" value="<?php echo $pass; ?>" required>
      </div>

      <button type="submit" class="btn btn-primary">Войти</button>

      <a href="index.php" class="btn btn-secondary">Назад</a>
    </form>
  </div>
</div>

</html>