<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<div class="container">
    <div class="row justify-content-md-center">
        <h3>Редактирование задачи</h3>
    </div>
    <div class="col-sm">
        <form action="edit.php" method="POST">
            <input type="hidden" name="_METHOD" value="PUT">

            <input name="id" type="hidden" value="<?php echo $task['id']; ?>">

            Редактирование задачи
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="completed" <?php if ($task['completed']) echo 'checked' ?> id="flexCheckChecked">
                <label class="form-check-label" for="flexCheckChecked">
                    Задача выполнена
                </label>
            </div>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Текст задачи</label>
                <textarea class="form-control" name="textTask" id="exampleFormControlTextarea1" rows="3"> <?php echo $task['texttask']; ?></textarea>
            </div>

            <button type="submit" class="btn btn-primary">Отредактровать задачу</button>
            <a href="tasks.php" class="btn btn-secondary">Назад</a>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>