<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row justify-content-md-center">
        <?php if ($viewEdit) : ?>
            <h3>Редактрирование задачи</h3>
        <?php endif ?>
        <?php if ($viewNewTask) : ?>
            <h3>Новая задача</h3>
        <?php endif ?>
    </div>
    <div class="col-sm">
        <form action="controllerTask.php" method="post">
            <?php if ($viewEdit) : ?>
                <input type="hidden" name="_METHOD" value="PUT">
                <input name="id" type="hidden" value="<?php echo $task['id']; ?>">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="completed" <?php if ($task['completed']) echo 'checked' ?> id="flexCheckChecked">
                    <label class="form-check-label" for="flexCheckChecked">
                        Задача выполнена
                    </label>
                </div>
            <?php endif ?>
            <?php if ($viewNewTask) : ?>
                <div class="mb-3">
                    <label class="form-label">Имя пользователя</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" name="email" id="exampleInputEmail1" required>
                </div>
            <?php endif ?>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Текст задачи</label>
                <textarea class="form-control" name="textTask" id="exampleFormControlTextarea1" rows="3" required><?php if ($viewEdit) : echo $task['texttask'];endif ?></textarea>
            </div>
            <?php if ($viewEdit) : ?>
                <button type="submit" class="btn btn-primary" name="saveTask">Отредактровать задачу</button>
            <?php endif ?>
            <?php if ($viewNewTask) : ?>
                <button type="submit" class="btn btn-primary" name="saveTask">Создать задачу</button>
            <?php endif ?>
        </form>
        <a href="index.php" class="btn btn-primary">Список задач</a>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>