<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row justify-content-md-center">
        <?php if (!$swithView) : ?>
            <h3>Редактирование задачи</h3>
       <?php else : ?>
            <h3>Новая задача</h3>
        <?php endif ?>
    </div>
    <div class="col-sm">
        <form action="controllerTask.php" method="post">
            <?php if (!$swithView) : ?>
                <input type="hidden" name="_METHOD" value="PUT">
                <input name="id" type="hidden" value="<?php echo $task['id']; ?>">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="completed" <?php if ($task['completed']) echo 'checked' ?> id="flexCheckChecked">
                    <label class="form-check-label" for="flexCheckChecked">
                        Задача выполнена
                    </label>
                </div>
           
                <?php endif ?>
                <div class="mb-3">
                    <label class="form-label">Имя пользователя</label>
                    <input type="text" class="form-control" id="name" name="name" <?php if (!$swithView) echo 'disabled' ?> 
                    value="<?php if (!$swithView) : echo $task['name'];endif ?>"required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" name="email" <?php if (!$swithView) echo 'disabled' ?> 
                    value="<?php if (!$swithView) : echo $task['email'];endif ?>"id="exampleInputEmail1" required>
                </div>
          

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label">Текст задачи</label>
                <textarea class="form-control" name="textTask" id="exampleFormControlTextarea1" rows="3" required><?php if (!$swithView) : echo $task['texttask'];endif ?></textarea>
            </div>
        
                <button type="submit" class="btn btn-primary" name="saveTask">Сохранить</button>
          
             
            
        </form>
        <a href="index.php" class="btn btn-primary">Список задач</a>
    </div>
</div>

</html>