<html>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>
  <div class="container">
    <div class="row justify-content-md-center">
      <h3>Список задач</h3>
    </div>
    <br>
    <?php if (!$editAllowed) : ?>
      <a href="authorization.php" class="btn btn-primary">Войти как администратор</a>
    <?php endif ?>
    <a href="newTask.phtml" class="btn btn-secondary">Новая задача</a>
    <?php if ($editAllowed) : ?>
      <a href="exit.php" class="btn btn-danger">Выйти</a>
    <?php endif ?>

    <form action="tasks.php" method="GET">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Имя пользоватлея <button type="submit" class="btn btn-link" name="sortingName">Сортировать</button></th>
            <th scope="col">Email address<button type="submit" class="btn btn-link" name="sortingEmail">Сортировать</button></th>
            <th scope="col">Текст задачи</th>
            <th scope="col">Статус<button type="submit" class="btn btn-link" name="sortingStatus">Сортировать</button></th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
    </form>
    <?php foreach ($tasks as $task) : ?>

      <tr>
        <th scope="row">
          <?php echo $task['id']; ?>
        </th>
        <td>
          <?php echo $task['name']; ?>
        </td>
        <td>
          <?php echo $task['email']; ?>
        </td>
        <td>
          <?php echo $task['texttask']; ?>
        </td>
        <td>
          <?php echo $task['completed']; ?>
        </td>
        <?php if ($editAllowed) : ?>
          <td>
            <a href="edit.php?id=<?php echo $task['id'] ?>">Редактировать</a>
          </td>
        <?php endif ?>

      </tr>

    <?php endforeach; ?>

    </tbody>
    </table>

    <div class="row">
      <div class="col">
        <?php if (!$preDisabled) :
          echo "<a href=tasks.php?page=" . $prePage . "> Предыдущая </a>";
        endif; ?>
      </div>
      <div class="col col-lg-2">
        <?php if (!$nextDisabled) :
          echo "<a href=tasks.php?page=" . $nextPage . "> Следующая  </a>";
        endif; ?>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>