<html>

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <div class="row justify-content-md-center">
      <h3>Список задач</h3>
    </div>
    <br>
    <?php if (!$editAllow) : ?>
      <a href="authorization.php" class="btn btn-primary">Войти как администратор</a>
    <?php endif ?>
    <a href="controllerTask.php?newTask" class="btn btn-secondary">Новая задача</a>
    <?php if ($editAllow) : ?>
      <a href="controllerTask.php?exit" class="btn btn-danger">Выйти</a>
    <?php endif ?>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Имя пользоватлея <a href="controllerTask.php?sortby=name" class="btn btn-link">Сортировать</a></th>
          <th scope="col">Email address<a href="controllerTask.php?sortby=email" class="btn btn-link">Сортировать</a></th>
          <th scope="col">Текст задачи</th>
          <th scope="col">Статус<a href="controllerTask.php?sortby=status" class="btn btn-link">Сортировать</a></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($taskList->tasks as $task) : ?>
          <tr>
            <th scope="row">
              <?php echo $task['id']; ?>
            </th>
            <td>
              <?php echo $task['name']; ?>
            </td>
            <td>
              <?php echo $task['email']; ?>
            </td>
            <td>
              <?php echo $task['texttask']; ?>
            </td>
            <td>
              <?php if ($task['completed']) : ?>
                отредактрированно администратором
              <?php endif ?>
            </td>
            <td>
              <?php if ($editAllow) : ?>
                <a href="controllerTask.php?id=<?php echo $task['id'] ?>">Редактировать</a>
              <?php endif ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>

    <div class="row">
      <div class="col">
        <?php if (!$preDisabled) :
          echo "<a href=controllerTask.php?page=" . $taskList->prePage . "&sortby=" . $taskList->sortListTask . "> Предыдущая </a>";
        endif; ?>
      </div>
      <div class="col col-lg-2">
        <?php if (!$nextDisabled) :
          echo "<a href=controllerTask.php?page=" . $taskList->nextPage . "&sortby=" . $taskList->sortListTask . "> Следующая  </a>";
        endif; ?>
      </div>
    </div>
  </div>
</body>

</html>